import { ease } from './anim_ease';
import { animateColor } from './animate_color';
import { animate, requestAnimFrame, cancelAnimFrame, runningAnimations } from './animate';
import { addListener, removeListener, getPointer, isTouchEvent } from './dom_event';
import { setImageSmoothing, getById, toArray, addClass, makeElement, wrapElement, getScrollLeftTop, getElementOffset, getNodeCanvas, cleanUpJsdomNode, makeElementUnselectable, makeElementSelectable } from './dom_misc';
import { request } from './dom_request';
import { setStyle } from './dom_style';
import { array } from './lang_array';
import { createClass } from './lang_class';
import { object } from './lang_object';
import { string } from './lang_string';
import { cos,
  sin,
  removeFromArray,
  getRandomInt,
  degreesToRadians,
  radiansToDegrees,
  rotatePoint,
  rotateVector,
  createVector,
  calcAngleBetweenVectors,
  getHatVector,
  getBisector,
  projectStrokeOnPoints,
  transformPoint,
  sendPointToPlane,
  transformPointRelativeToCanvas,
  makeBoundingBoxFromPoints,
  invertTransform,
  toFixed,
  parseUnit,
  falseFunction,
  getKlass,
  getSvgAttributes,
  resolveNamespace,
  loadImage,
  enlivenObjects,
  enlivenObjectEnlivables,
  groupSVGElements,
  populateWithProperties,
  createCanvasElement,
  copyCanvasElement,
  toDataURL,
  createImage,
  multiplyTransformMatrices,
  qrDecompose,
  calcRotateMatrix,
  calcDimensionsMatrix,
  composeMatrix,
  resetObjectTransform,
  saveObjectTransform,
  isTransparent,
  parsePreserveAspectRatioAttribute,
  clearFabricFontCache,
  limitDimsByArea,
  capValue,
  findScaleToFit,
  findScaleToCover,
  matrixToSVG,
  removeTransformFromObject,
  addTransformToObject,
  applyTransformToObject,
  sendObjectToPlane,
  sizeAfterTransform,
  mergeClipPaths, } from './misc';
import { createAccessors } from './named_accessors.mixin'
import { joinPath,
  parsePath,
  makePathSimpler,
  getSmoothPathFromPoints,
  getPathSegmentsInfo,
  getBoundsOfCurve,
  getPointOnPath,
  transformPath,
  getRegularPolygonPath } from './path'
import { Observable } from '../mixins/observable.mixin';

const util = {
  ease,
  animateColor,
  animate,
  requestAnimFrame,
  cancelAnimFrame,
  addListener,
  removeListener,
  getPointer,
  isTouchEvent,
  setImageSmoothing,
  getById,
  toArray,
  addClass,
  makeElement,
  wrapElement,
  getScrollLeftTop,
  getElementOffset,
  getNodeCanvas,
  cleanUpJsdomNode,
  makeElementUnselectable,
  makeElementSelectable,
  request,
  setStyle,
  array,
  createClass,
  string,
  cos,
  sin,
  removeFromArray,
  getRandomInt,
  degreesToRadians,
  radiansToDegrees,
  rotatePoint,
  rotateVector,
  createVector,
  calcAngleBetweenVectors,
  getHatVector,
  getBisector,
  projectStrokeOnPoints,
  transformPoint,
  sendPointToPlane,
  transformPointRelativeToCanvas,
  makeBoundingBoxFromPoints,
  invertTransform,
  toFixed,
  parseUnit,
  falseFunction,
  getKlass,
  getSvgAttributes,
  resolveNamespace,
  loadImage,
  enlivenObjects,
  enlivenObjectEnlivables,
  groupSVGElements,
  populateWithProperties,
  createCanvasElement,
  copyCanvasElement,
  toDataURL,
  createImage,
  multiplyTransformMatrices,
  qrDecompose,
  calcRotateMatrix,
  calcDimensionsMatrix,
  composeMatrix,
  resetObjectTransform,
  saveObjectTransform,
  isTransparent,
  parsePreserveAspectRatioAttribute,
  clearFabricFontCache,
  limitDimsByArea,
  capValue,
  findScaleToFit,
  findScaleToCover,
  matrixToSVG,
  removeTransformFromObject,
  addTransformToObject,
  applyTransformToObject,
  sendObjectToPlane,
  sizeAfterTransform,
  mergeClipPaths,
  createAccessors,
  joinPath,
  parsePath,
  makePathSimpler,
  getSmoothPathFromPoints,
  getPathSegmentsInfo,
  getBoundsOfCurve,
  getPointOnPath,
  transformPath,
  getRegularPolygonPath
}

object.extend(util, Observable);

export { 
  util,
  runningAnimations 
};